### ISSUE TITLE
calendar_watcher の setup コマンドを作る

### ISSUE THREAD

**Issue by taccho918** [nomlab/hiyoco#16]
Created from [AI0542](http://jay.swlab.cs.okayama-u.ac.jp/minutes/664?ai=0542) of minute 664.
+ calendar_watcher の setup コマンドを作る． -->(石川，高橋 !:0542)

**Comment by HiromuIshikawa** [comment]
#11 に結びついた PR が merge されてから，PR をmerge し，close する．
